config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks',
      unlocks: 'users/unlocks'
    }

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index]
    resources :events, only: [:index]

    resources :records, only: [] do
      collection do
        get :latest_ts
      end
    end
  end

  root 'welcome#index'
  get '/current', to: 'welcome#current'
  get '/pending', to: 'welcome#pending'

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :projects
  resources :memberships, only: [:edit, :update, :destroy]
  resources :periods do
    member do
      put 'add_member'
    end
  end

  resources :records, only: [:index, :create, :update] do
    member do
      put 'leave'
    end
  end

end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :projects

  enum code: [:project, :community, :academy, :others]
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :add_member, :destroy]

  def index
    @periods = Period.all.order(number: :asc)
  end

  def show
    @memberships = @period.memberships.order(paak_id: :asc)
    @user_candidate = User.candidate
  end

  def new
    @period = Period.new
  end

  def edit
  end

  def create
    @period = Period.new(period_params)

    if @period.save
      redirect_to @period, notice: 'Period was successfully created.' and return
    else
      render :new
    end
  end

  def update
    if @period.update(period_params)
      redirect_to @period, notice: 'Period was successfully updated.' and return
    else
      render :edit
    end
  end

  def add_member
    Membership.new({period_id: @period.id}.merge(add_member_params)).save!
    redirect_to @period, notice: 'メンバーが追加されました' and return
  end

  def destroy
    # if @period.destroy
    #   redirect_to periods_url, notice: 'Period was successfully destroyed.' and return
    # end
    redirect_to periods_url, notice: 'この機能は無効になっています' and return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:number, :code, :explanation, :start_date, :end_date)
    end

    def add_member_params
      params.permit(:paak_id, :user_id, :name, :memo)
    end
end

app/views/periods/_add_member_form.html.erb
<%= form_tag add_member_period_path, method: :put, class: 'form-inline' do %>
  <div class='form-group'>
    <%= number_field_tag :paak_id, params[:paak_id], class: 'form-control', placeholder: '会員番号' %>
  </div>
  <div class='form-group'>
    <%= text_field_tag :name, params[:name], class: 'form-control', placeholder: '名前' %>
  </div>
  <div class='form-group'>
    <%= select_tag :user_id, options_for_select(@user_candidate.map{|user| [user.name, user.id]}), class: 'form-control', prompt: 'ユーザーを選択（任意）' %>
  </div>
  <div class='form-group'>
    <%= text_field_tag :memo, params[:memo], class: 'form-control', placeholder: 'メモ（任意）' %>
  </div>
  <div class='form-group'>
    <%= submit_tag "追加する", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/periods/_form.html.erb
<%= form_for(@period, html:{class: 'form-normal'}) do |f| %>
  <% if @period.errors.any? %>
    <div id='error_explanation' class='bg-danger'>
      <h2><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% @period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label '名前' %><br>
    <%= f.text_field :explanation, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label '期' %><br>
    <%= f.number_field :number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label '会員種別' %><br>
    <%= f.select :code, Period.codes.keys.to_a, {}, class: 'form-control' %>
  </div>
  <div class="form-group form-inline">
    <%= f.label '期間' %><br>
    <%= f.date_field :start_date, class: 'form-control' %>
    〜
    <%= f.date_field :end_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit '保存', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/periods/_members.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>paak会員番号</th>
      <th>paak登録名</th>
      <th>ユーザー名</th>
      <th>メモ</th>
      <th>facebook</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% memberships.each do |membership| %>
      <tr>
        <td><%= membership.paak_id %></td>
        <td><%= membership.name %></td>
        <td><%= membership.user.try(:name) %></td>
        <td><%= (membership.memo.try(:length) || 0) > 20 ? "#{membership.memo[0, 20]}..." : membership.memo %></td>
        <td>
          <% if membership.user.try(:facebook_url).present? %>
            <%= link_to membership.user.facebook_url do %>
              <span class='fa fa-facebook' />
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'ユーザーを見る', membership.user if membership.user.present? %></td>
        <td><%= link_to 'メンバーシップの編集', edit_membership_path(membership) %></td>
        <td><%= link_to 'メンバーから削除', membership, method: :delete, data: { confirm: 'ユーザーは削除されません。メンバーシップのみ削除されます。よろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/periods/edit.html.erb
<h1 class='title'>期・メンバーシップの編集</h1>

<%= render 'form' %>

<%= link_to '戻る', @period, class: 'btn btn-default' %>

app/views/periods/index.html.erb
<h1 class='title'>期・メンバーシップ　一覧</h1>

<table class='table'>
  <thead>
    <tr>
      <th>期</th>
      <th>メンバー種別</th>
      <th>名前</th>
      <th>期間</th>
      <th>メンバー数</th>
      <th></th>
      <!-- <th></th> -->
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= period.number %></td>
        <td><%= period.code %></td>
        <td><%= period.explanation %></td>
        <td><%= "#{period.start_date}〜#{period.end_date}" if period.start_date || period.end_date %></td>
        <td><%= period.memberships.count %></td>
        <td><%= link_to '詳細を見る', period %></td>
        <!-- <td><%= link_to '削除', period, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_period_path, class: 'btn btn-default' %>

app/views/periods/new.html.erb
<h1 class='title'>期・メンバーシップの作成</h1>

<%= render 'form' %>

<%= link_to '戻る', periods_path, class: 'btn btn-default' %>

app/views/periods/show.html.erb
<h1 class='title'><%= @period.explanation %></h2>

<p>
  <strong>期（数字）</strong>
  <%= @period.number %>
</p>

<p>
  <strong>メンバー種別</strong>
  <%= @period.code %>
</p>

<% if @period.start_date || @period.end_date %>
  <p>
    <strong>期間</strong>
    <%= "#{@period.start_date}〜#{@period.end_date}" %>
  </p>
<% end %>

<%= link_to '編集', edit_period_path(@period), class: 'btn btn-default' %>
<%= link_to '戻る', periods_path, class: 'btn btn-default' %>

<% if @memberships.present? %>
  <hr>
  <h2 class='sub-title'>メンバー一覧</h2>
  <%= render 'periods/members', memberships: @memberships %>
<% end %>

<hr>
<h2 class='sub-title'>メンバー追加</h2>
<%= render 'periods/add_member_form' %>