config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks',
      unlocks: 'users/unlocks'
    }

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index]
    resources :events, only: [:index]

    resources :records, only: [] do
      collection do
        get :latest_ts
      end
    end
  end

  root 'welcome#index'
  get '/current', to: 'welcome#current'
  get '/pending', to: 'welcome#pending'

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :projects
  resources :memberships, only: [:edit, :update, :destroy]
  resources :periods do
    member do
      put 'add_member'
    end
  end

  resources :records, only: [:index, :create, :update] do
    member do
      put 'leave'
    end
  end

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :membership

  enum code: [:enter, :leave]
end

app/controllers/api/records_controller.rb
class Api::RecordsController < Api::BaseController
  skip_before_action :authenticate_admin!

  def latest_ts
    render json: {
      ts: Record.order(timestamp: :desc).first.try(:timestamp).try(:to_i) || 1
      }.to_json
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    Time.zone = 'Tokyo'
    date = params[:period].try(:to_date) || Time.now.to_date

    @records = Record.order(timestamp: :desc).where('timestamp >= ? AND timestamp < ?', date, date + 1.day)
  end

  def create
    redirect_to :back, alert: '会員種別を指定してください' and return unless params[:period_code].present?

    membership = Membership.by_period_code(params[:period_code]).find_by(paak_id: params[:paak_id])
    redirect_to :back, alert: '存在しない会員です' and return unless membership

    @record = Record.new(membership: membership, timestamp: DateTime.now, card_id: params[:card_id], memo: params[:memo])
    if params[:commit].to_sym == :enter then @record.enter! else @record.leave! end

    if @record.save
      redirect_to records_path, notice: '記録が残されました' and return
    else
      render :back, alert: '記録に失敗しました'
    end
  end

  def update
    @record = Record.find_by(id: params[:id])
    @record.memo = params[:memo]
    if @record.save!
      redirect_to records_path, notice: 'メモが変更されました' and return
    else
      render :back, alert: 'メモの編集に失敗しました' and return
    end
  end

  def leave
    @old_record = Record.find_by(id: params[:id])
    @record = Record.new(membership: @old_record.membership, timestamp: DateTime.now, card_id: @old_record.card_id)
    @record.leave!
    if @record.save!
      redirect_to records_path, notice: '退館が完了しました' and return
    else
      render :back, alert: '退館に失敗しました' and return
    end
  end
end

app/views/records/index.html.erb
<h1 class='title'>
  入退館記録
  <%= form_tag records_path, method: :get, class: 'record-search-form form-inline' do %>
    <div class="form-group">
      <%= select_tag :period, options_for_select(((Date.today - 31.day)..(Date.today)).to_a.reverse, params[:period]), class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= submit_tag :search, class: 'btn btn-default' %>
    </div>
  <% end %>
</h1>

<%= form_tag records_path, method: :post, class: 'record-form form-inline' do %>
  <div class="form-group">
    <%= select_tag :period_code, options_for_select(Period.codes.keys.to_a), prompt: '会員種別', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= number_field_tag :paak_id, params[:paak_id], class: 'form-control', placeholder: '会員番号' %>
  </div>
  <div class='form-group'>
    <%= text_field_tag :card_id, params[:card_id], class: 'form-control', placeholder: 'カード番号（任意）' %>
  </div>
  <div class='form-group'>
    <%= text_field_tag :memo, params[:memo], class: 'form-control', placeholder: 'メモ（任意）' %>
  </div>
  <div class='form-group'>
    <%= submit_tag :enter, class: 'btn btn-primary' %>
  </div>
  <div class='form-group'>
    <%= submit_tag :leave, class: 'btn btn-danger' %>
  </div>
<% end %>

<table class='table records-table'>
  <thead>
    <tr>
      <th>期</th>
      <th>メンバー種別</th>
      <th>会員番号</th>
      <th>名前</th>
      <th>時間</th>
      <th>カード番号</th>
      <th>メモ</th>
      <th colspan='2'></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.membership.try(:period).try(:explanation) || '削除済み' %></td>
        <td><%= record.membership.try(:period).try(:code) || '削除済み' %></td>
        <td><%= record.membership.try(:paak_id) || '削除済み' %></td>
        <td><%= record.membership.try(:name).try(:[], 0, 8) || '削除済み' %></td>
        <td><%= record.timestamp.in_time_zone('Tokyo') %></td>
        <td><%= record.card_id %></td>
        <td>
          <%= form_tag record_path(record.id), method: :put, class: 'form-inline' do %>
            <div class="form-group">
              <%= text_field_tag :memo, record.memo, prompt: '会員種別', class: 'form-control' %>
            </div>
            <div class='form-group'>
              <%= submit_tag '保存', class: 'btn btn-default', data: { disable_with: "保存中..." } %>
            </div>
          <% end %>
        </td>
        <td class='record-code'>
          <% if record.code == 'enter' %>
            <span class='text-primary'>入館</span>
          <% elsif record.code == 'leave' %>
            <span class='text-danger'>退館</span>
          <% end %>
        </td>
        <td class='record-code'>
          <% if Membership.find_by(id: record.membership_id) && Membership.find_by(id: record.membership_id).last_record_id == record.id && record.enter? %>
            <%= form_tag leave_record_path(record.id), method: :put, class: 'form-inline' do %>
              <div class='form-group'>
                <%= submit_tag '退館させる', class: 'btn btn-danger' %>
              </div>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>