config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks',
      unlocks: 'users/unlocks'
    }

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index]
    resources :events, only: [:index]

    resources :records, only: [] do
      collection do
        get :latest_ts
      end
    end
  end

  root 'welcome#index'
  get '/current', to: 'welcome#current'
  get '/pending', to: 'welcome#pending'

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :projects
  resources :memberships, only: [:edit, :update, :destroy]
  resources :periods do
    member do
      put 'add_member'
    end
  end

  resources :records, only: [:index, :create, :update] do
    member do
      put 'leave'
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>
    <%= link_to 'TECH LAB PAAK', 'http://techlabpaak.com/' %>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About',   'http://techlabpaak.com/about' %></li>
      <li><%= link_to 'Contact', 'http://techlabpaak.com/contact' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="header-container">
    <div class='navbar-header'>
      <button class="navbar-toggle collapsed"
              data-toggle="collapse"
              data-target="#paak-navbar-collapse"
              aria-expanded="false">
        <span class="icon-bar icon-bar--top"></span>
        <span class="icon-bar icon-bar--middle"></span>
        <span class="icon-bar icon-bar--bottom"></span>
      </button>
      <%= link_to "TECH LAB PAAK Members", root_path, id: "logo", class: 'bavbar-brand text-muted pull-left' %>
    </div>

    <div class='collapse navbar-collapse' id='paak-navbar-collapse'>
      <ul class="nav navbar-nav navbar-left">
        <% if current_user %>
          <% if current_user.is_admin %>
            <li><%= link_to "Admin:メンバー管理", periods_path %></li>
            <li><%= link_to "Admin:入退館", records_path %></li>
          <% end %>
          <li><%= link_to "メンバー", users_path %></li>
          <li><%= link_to "プロジェクト", projects_path %></li>
          <li><%= link_to "マイページ", user_path(current_user) %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaakCommunity</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% if notice.present? %>
      <p class="bg-info main-notification"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="bg-danger main-notification"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  <%= render 'shared/ga' %>
  <%= render 'shared/js' %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaakCommunity</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% if notice.present? %>
      <p class="bg-info main-notification"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="bg-danger main-notification"><%= alert %></p>
    <% end %>
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </div>
  <%= render 'shared/ga' %>
  <%= render 'shared/js' %>
</body>
</html>